### ISSUE TITLE
[BUG] `switch_play_server` Response Not Always Obeyed

### ISSUE THREAD

**Issue by Emmotes** [djravine/idlecombos#81]
Heya

Currently you've got it set up so that if getting user details returns with a `switch_play_server` response IdleCombos will obey it. But for a while now - every single server call that returns with the `switch_play_server` response must be obeyed. Otherwise the server will simply ignore the call and fail. And pretty much every call that deals with user details in any way can respond with it.

So this is causing some issues with code redemption and blacksmith contract use etc. unless the server in the settings is set to what the game is currently using.

**Comment by djravine** [comment]
I just released v3.64 with the `switch_play_server` code detection in the server calls function.

https://github.com/djravine/idlecombos/blob/9d0948b72d6c936dbc3377380a72eea5a796da18/IdleCombos.ahk#L3579

**Comment by djravine** [comment]
Oh, I think I have a bug with the data variable.

**Comment by Emmotes** [comment]
That's bizarre. I downloaded it and tested it (noticed it wasn't working) and went to check. I could only see one instance of `switch_play_server` in the user details. But now I check I can see two and I haven't updated since. Not sure what's going on.

But yeah - there's definitely still an issue. I just tried again with a redeem code and it gets `Unknown or No Results`.
If you know the bug though - all good.

**Comment by djravine** [comment]
Yeah, I found a variable bug, just about to push a new version. One sec

**Comment by djravine** [comment]
https://github.com/djravine/idlecombos/releases/tag/v3.66

**Comment by djravine** [comment]
Let me know if this new version works and I'll close this issue. 🤞

**Comment by Emmotes** [comment]
Hm I'm not sure. Gave it a try and it's getting `Unknown or No Results` from code redemption with both the correct and wrong server.

But applying blacksmith contracts seems to work regardless so the server swap seems to be fixed.

**Comment by VoltageMiner** [comment]
Tried to redeem a code and got `Unknown or No Results`. The redeemcodelog.json told me that `"success":true,"switch_play_server":"http:\/\/ps22.idlechampions.com\/~idledragons\/"`. I had to manually set the sever in the settings to get it to work. The `Get Play Server Name automatically?` setting is enabled.
